name: Upload Python Package

# 触发条件为当 GitHub Release 发布时
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    # 拉取最新代码
    - name: Checkout latest code
      uses: actions/checkout@v4  # 确保拉取的是最新的代码

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # 清理 dist 文件夹，确保没有旧的打包文件
    - name: Clean dist folder
      run: rm -rf dist

    # 安装构建工具和依赖项
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    # 检查 config.ini 文件的内容，确保最新版本
    - name: Check config.ini contents
      run: cat fastshot/config.ini  # 这一步是可选的，可以帮助你确认 config.ini 是最新的

    # 构建项目
    - name: Build package
      run: python -m build  # 使用 python -m build 打包

    # 发布到 PyPI
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0  # 使用 PyPI 发布 Action
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}  # 使用 GitHub secrets 中的 PYPI_API_TOKEN
        skip_existing: true  # 如果文件已存在，跳过上传